data_File <- "./data/household_power_consumption.txt"
ecc_data <- read.table(data_File, header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
sub_data_range <- ecc_data[ecc_data$Date %in% c("1/2/2007","2/2/2007") ,]
#str(subSetData)
date_time <- strptime(paste(sub_data_range$Date, sub_data_range$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2)) 
plot(date_time, as.numeric(sub_data_range$Global_active_power), type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(date_time, as.numeric(sub_data_range$Voltage), type="l", xlab="datetime", ylab="Voltage")
plot(date_time, as.numeric(sub_data_range$Sub_metering_1), type="l", ylab="Energy Submetering", xlab="")
lines(date_time, as.numeric(sub_data_range$Sub_metering_1), type="l", col="red")
lines(date_time, as.numeric(sub_data_range$Sub_metering_1), type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(date_time, as.numeric(sub_data_range$Global_reactive_power), type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()